### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [microsoft/clarity-gtm-template#3]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) encodeUri should be used on user provided url values that are used to create your url. These methods return an encoded Uniform Resource Identifier (URI) by escaping special characters. This method returns a string that represents the provided string encoded as a URI. You should use this method on "data.projectId" when generating the url
const url = "https://www.clarity.ms/tag/"+data.projectId;

**Comment by q3blend** [comment]
Fixed in PR #5 

Another question. I noticed there is a community gallery, but there's also a gallery of official tags on GTM when you go **Tags > New > Tag Configuration > More** as in the attached screenshot. How can I get my tag added there as well as these seem to be the official tags.
![Capture](https://user-images.githubusercontent.com/2285634/107020695-d8d77700-67ab-11eb-9501-40f572184df7.JPG)

**Comment by q3blend** [comment]
@praveena-pappu I've updated the SHA to reflect the fix and resubmitted the template for validation
